export const FETCH_ALL_CUSTOMERS = "FETCH_ALL_CUSTOMERS";

export const FETCH_ADDED_CUSTOMER = "FETCH_ADDED_CUSTOMER";

export const FETCH_PAID_CUSTOMER = "FETCH_PAID_CUSTOMER";

export const DELETE_PRODUCT_FROM_CUSTOMER = "DELETE_PRODUCT_FROM_CUSTOMER";

export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";